### ISSUE TITLE
TypeError: ECPrivateKey.sign() got an unexpected keyword argument 'signature_algorithm'

### ISSUE THREAD

**Issue by lucas-mmb** [pyca/cryptography#10237]
The imgtool script I was using to sign some firmware images broke in the pipeline since updating to v42.
Earlier today it was working fine with cryptography-41.0.7

https://github.com/nrfconnect/sdk-mcuboot

  File "/usr/local/lib/python3.10/dist-packages/imgtool/main.py", line 475, in sign
    img.create(key, public_key_format, enckey, dependencies, boot_record,
  File "/usr/local/lib/python3.10/dist-packages/imgtool/image.py", line 481, in create
    sig = key.sign(bytes(self.payload))
  File "/usr/local/lib/python3.10/dist-packages/imgtool/keys/ecdsa.py", line 208, in sign
    sig = self.raw_sign(payload)
  File "/usr/local/lib/python3.10/dist-packages/imgtool/keys/ecdsa.py", line 203, in raw_sign
    return self.key.sign(
TypeError: ECPrivateKey.sign() got an unexpected keyword argument 'signature_algorithm'

**Comment by reaperhulk** [comment]
Thanks for the report, this is a bug we'll fix for 42.0.1 (we accidentally changed a kwarg and don’t appear to have a test for passing as kwarg)

**Comment by moculll** [comment]
> Thanks for the report, this is a bug we'll fix for 42.0.1 (we accidentally changed a kwarg and don’t appear to have a test for passing as kwarg)

Thanks, dude, 42.0.1 works pretty well
