### ISSUE TITLE
cannot build on OSX 10.10.3 with gcc 4.9.2

### ISSUE THREAD

**Issue by dimpase** [pyca/cryptography#1924]
We get 

    In file included from /System/Library/Frameworks/Security.framework/Headers/SecDigestTransform.h:28:0,
                     from src/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_2a871178xb3816a41.c:236:
    /System/Library/Frameworks/Security.framework/Headers/SecTransform.h:579:15: error: expected identifier or '(' before '^' token
     typedef void (^SecMessageBlock)(CFTypeRef message, CFErrorRef error, 
                   ^
    /System/Library/Frameworks/Security.framework/Headers/SecTransform.h:612:8: error: unknown type name 'SecMessageBlock'
            SecMessageBlock deliveryBlock) 
            ^
    error: command 'gcc' failed with exit status 1

Does it mean one is out of luck here? For it appears that the OSX header is clang-only...

**Comment by reaperhulk** [comment]
That is correct, unfortunately C blocks are a clang only feature. We could potentially add a flag to disable compilation of the OS X specific bits (they are located in the commoncrypto backend), but for now we support building with clang only.

**Comment by dimpase** [comment]
Can one instead use the OpenSSL built from source, instead of Apple's ssl?
I tried to follow https://cryptography.io/en/latest/installation/#using-your-own-openssl-on-linux but  it ends up with the same errors as above.

**Comment by reaperhulk** [comment]
The issue is not OpenSSL but that cryptography has multiple backends. OpenSSL has no blocks (not even Apple's fork) but the other backend we build on OS X, commoncrypto, does.

Is there a specific requirement you have to build using gcc on OS X rather than system clang? If there is, you can work around this by patching cc_is_available in setup.py to return false.

**Comment by dimpase** [comment]
Thanks, this helps. We cannot really use clang, as we need (g)fortran. 

Any chance you might consider providing an option that disables building commoncrypto, so that cryptography can still be installed with pip?

**Comment by reaperhulk** [comment]
Hmm, will have to think about that. Introspecting the compiler used is difficult and I'm reluctant to force explicit use of a flag. Out of curiosity, would there be any reason why you couldn't do ``CC=clang pip install cryptography`` during your build? The use of gfortran is obviously not tied to cryptography directly and the compiled libraries should be capable of interacting, right?

**Comment by dimpase** [comment]
All I'm asking for is that `cc_is_available` first of all to does

      import os
      if 'NOCOMMONCRYPTO' in os.environ: 
            return False

We don't want to rely on Apple's toolchain at all, as it proves to be a major pain in our project (http://sagemath.org). 

Besides, a user should have a choice of not having an unneeded closed source crypto backend in the python stack!

**Comment by dimpase** [comment]
wow, there is even http://www.zazzle.com/goto_fail_t_shirt_plain_code-235322391420181248 :-)

**Comment by Ayrx** [comment]
@dimpase I support the idea of a flag to explicitly disable compiling the CommonCrypto backend but you are incorrect in saying that CommonCrypto is close sourced. :)

**Comment by reaperhulk** [comment]
A few th

**Comment by reaperhulk** [comment]
A few thoughts here:

* We require full coverage for any change we make which means adding a flag like this will require us to add a new builder to test that it works. This is doable but something to be aware of.
* SecureTransport (the source of goto fail) is not currently bound, although given that every single major TLS stack has had a critical failure in the last 12 months it's a bit of a glass house situation.
* You can precisely control which backend is used by importing it directly rather than using default_backend.
* We do have plans to eventually split the backends out so users can explicitly choose which ones they want installed (#1473 and #1522)

I think we'll probably add the flag until we get around to splitting the backends. Maybe for 0.10?

**Comment by reaperhulk** [comment]
It's been decided that this is best addressed via optional backends (#1473 and #1522), which will appear in a future version. For now, the simple setup.py patch can be used to prevent compilation of the undesired backend.
