### PR TITLE
Order the pem binding before engine to build with OpenSSL 1.1.1

### PR DESCRIPTION
**Pull request by Saur2000**
This avoids the following errors:

  In file included from
  build/temp.linux-x86_64-cpython-311/cryptography.hazmat.bindings._openssl.c:669:
  /usr/include/openssl/engine.h:272:40: error: unknown type name
  ‘pem_password_cb’
    272 |                                        pem_password_cb *pwd_callback,
        |                                        ^~~~~~~~~~~~~~~
  /usr/include/openssl/engine.h:487:42: error: unknown type name
  ‘ENGINE_LOAD_KEY_BIO_PTR’; did you mean ‘ENGINE_LOAD_KEY_PTR’?
    487 |                                          ENGINE_LOAD_KEY_BIO_PTR loadpriv_f);
        |                                          ^~~~~~~~~~~~~~~~~~~~~~~
        |                                          ENGINE_LOAD_KEY_PTR
  /usr/include/openssl/engine.h:531:1: error: unknown type name
  ‘ENGINE_LOAD_KEY_BIO_PTR’; did you mean ‘ENGINE_LOAD_KEY_PTR’?
    531 | ENGINE_LOAD_KEY_BIO_PTR ENGINE_get_load_privkey_bio_function(const ENGINE *e);
        | ^~~~~~~~~~~~~~~~~~~~~~~
        | ENGINE_LOAD_KEY_PTR
  /usr/include/openssl/engine.h:597:33: error: unknown type name
  ‘pem_password_cb’
    597 |                                 pem_password_cb *cb, void *cb_data);
        |                                 ^~~~~~~~~~~~~~~

### CODE REVIEW

**Comment by reaperhulk** [comment]
We build with 1.1.1 versions in multiple places in our CI, can you give us a few more details so we can understand why we’re not seeing this in CI?

**Comment by Saur2000** [comment]
We are using Poky from the Yocto Project to build embedded firmware for our products. I got the problem building the `python3-cryptography-native` recipe when it was updated to version 39.0.0. While this was with `master` of Poky, we have reverted the `openssl` recipe to version 1.1.1s in our environment. OpenSSL is configured with `--with-rand-seed=os,devrandom disable-devcryptoeng no-ssl no-idea no-rc5 no-md2 no-camellia no-mdc2 no-seed no-siphash no-sm2 no-sm3 no-sm4`.

**Comment by reaperhulk** [comment]
I just built a 1.1.1s using the flags you specified and can't replicate the compile issue. `/usr/include/openssl/engine.h:272` line 272 doesn't contain anything about `pem_password_cb` (and there appear to be no references to it at all in `engine.h`). I'm not opposed to landing this, but I'm still confused right now!

**Comment by Saur2000** [comment]
Thank you for looking into it. It appears we have a local patch that adds the functions using `pem_password_cb`. After correcting that patch everything now works as expected. Since the error is clearly on our side, I will close this issue. Sorry for taking up your time.
