### ISSUE TITLE
Getting Error while installing cryptography

### ISSUE THREAD

**Issue by siddharth15o2** [pyca/cryptography#7521]
Python version: 3.8.0a2-alpine3.9
Cryptography version: 37.0.4
Pip version: 22.2.2
setuptools version: 65.0.2
OpenSSL version: not showing
cffi version: not showing

* How you installed ``cryptography``: I am trying to install it Inside docker container

* Clear steps for reproducing your bug
   - before updating pip version
   - pip install cryptography
```
Collecting cryptography
  Downloading https://files.pythonhosted.org/packages/89/d9/5fcd312d5cce0b4d7ee8b551a0ea99e4ea9db0fdbf6dd455a19042e3370b/cryptography-37.0.4.tar.gz (585kB)
    100% |████████████████████████████████| 593kB 6.4MB/s 
  Installing build dependencies ... error
  Complete output from command /usr/local/bin/python /usr/local/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-xl061o5c/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools>=40.6.0,!=60.9.0 wheel "cffi>=1.12; platform_python_implementation != 'PyPy'" setuptools-rust>=0.11.4:
  Collecting setuptools!=60.9.0,>=40.6.0
    Using cached https://files.pythonhosted.org/packages/02/70/40276081ce5d29e7610618a857909e4eba264c0c9cfb4ecb613a4f7ad0ef/setuptools-65.0.2-py3-none-any.whl
  Collecting wheel
    Downloading https://files.pythonhosted.org/packages/27/d6/003e593296a85fd6ed616ed962795b2f87709c3eee2bca4f6d0fe55c6d00/wheel-0.37.1-py2.py3-none-any.whl
  Collecting cffi>=1.12
    Downloading https://files.pythonhosted.org/packages/2b/a8/050ab4f0c3d4c1b8aaa805f70e26e84d0e27004907c5b8ecc1d31815f92a/cffi-1.15.1.tar.gz (508kB)
      Complete output from command python setup.py egg_info:
      /usr/local/lib/python3.8/site-packages/setuptools/config/setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/tmp/pip-install-78fmiqyw/cffi/setup.py", line 179, in <module>
          setup(
        File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/usr/local/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 172, in setup
          ok = dist.parse_command_line()
        File "/usr/local/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 479, in parse_command_line
          args = self._parse_command_opts(parser, args)
        File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 1107, in _parse_command_opts
          nargs = _Distribution._parse_command_opts(self, parser, args)
        File "/usr/local/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 538, in _parse_command_opts
          cmd_class = self.get_command_class(command)
        File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 954, in get_command_class
          self.cmdclass[command] = cmdclass = ep.load()
        File "/usr/local/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 194, in load
          module = import_module(match.group('module'))
        File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
        File "<frozen importlib._bootstrap>", line 991, in _find_and_load
        File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 777, in exec_module
        File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
        File "/usr/local/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 24, in <module>
          from setuptools.command.sdist import sdist
        File "/usr/local/lib/python3.8/site-packages/setuptools/command/sdist.py", line 12, in <module>
          from .build import _ORIGINAL_SUBCOMMANDS
        File "/usr/local/lib/python3.8/site-packages/setuptools/command/build.py", line 9, in <module>
          from typing import Protocol
      ImportError: cannot import name 'Protocol' from 'typing' (/usr/local/lib/python3.8/typing.py)
```

* After upgrading pip from 19 to 22:
```
    Collecting pip
  Downloading https://files.pythonhosted.org/packages/1f/2c/d9626f045e7b49a6225c6b09257861f24da78f4e5f23af2ddbdf852c99b8/pip-22.2.2-py3-none-any.whl (2.0MB)
    100% |████████████████████████████████| 2.0MB 7.7MB/s 
Installing collected packages: pip
  Found existing installation: pip 19.0.3
    Uninstalling pip-19.0.3:
      Successfully uninstalled pip-19.0.3
Successfully installed pip-22.2.2
bash-4.4# pip3 install cryptography
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 6, in <module>
    from pip._internal.cli.main import main
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/cmdoptions.py", line 24, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/configuration.py", line 20, in <module>
    from pip._internal.exceptions import (
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/exceptions.py", line 14, in <module>
    from pip._vendor.rich.console import Console, ConsoleOptions, RenderResult
  File "/usr/local/lib/python3.8/site-packages/pip/_vendor/rich/console.py", line 38, in <module>
    from typing import Literal, Protocol, runtime_checkable
ImportError: cannot import name 'Literal' from 'typing' (/usr/local/lib/python3.8/typing.py)
```

* Docker file:
```
FROM python:3.8.0a2-alpine3.9

RUN apk update \
    && apk add --no-cache --virtual bash \
    && apk add gcc \
    && apk add musl-dev \
    && apk add linux-headers \
    && apk add jpeg-dev \
    && apk add zlib-dev \
    && apk add mariadb-dev \
    && apk add libffi-dev \
    && apk add postgresql-dev 

RUN apk update && apk upgrade && \
    echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories && \
    echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories && \ 
    apk add --no-cache curl jq python3 py3-pip && \
    apk add --no-cache \
    yarn \
    bash \
    git \
    openssh \
    build-base \
    gcc \
    wget

RUN pip install uwsgi

RUN pip install -r requirements.txt
```

**Comment by alex** [comment]
The problem is that you are using python 3.8 alpha2. setuptools only supports python official releases. Since Python 3.8 was released many years ago, you should just switch to using the official release, and not the alpha.
