### ISSUE TITLE
Cargo.toml should require asn1 >= 0.6.4

### ISSUE THREAD

**Issue by tiran** [pyca/cryptography#6337]
The ``Cargo.toml`` of release 35.0.0 requires asn1 0.6:

```
asn1 = { version = "0.6", default-features = false, features = ["derive"] }
```

The version requirement is too relaxed. Cryptography fails to build with asn1 0.6.1:

```
   --> src/x509.rs:421:10
    |
421 | #[derive(asn1::Asn1Read, asn1::Asn1Write)]
    |          ^^^^^^^^^^^^^^
    |
    = help: message: called `Result::unwrap()` on an `Err` value: Error("unexpected token")
error: proc-macro derive panicked
   --> src/x509.rs:421:26
    |
421 | #[derive(asn1::Asn1Read, asn1::Asn1Write)]
    |                          ^^^^^^^^^^^^^^^
    |
    = help: message: called `Result::unwrap()` on an `Err` value: Error("unexpected token")
error[E0599]: no method named `len` found for struct `SequenceOf` in the current scope
  --> src/ocsp.rs:46:52
   |
46 |     if raw.borrow_value().tbs_request.request_list.len() != 1 {
   |                                                    ^^^ method not found in `SequenceOf<'_, Request<'_>>`
error[E0599]: no method named `len` found for struct `SequenceOf` in the current scope
   --> src/ocsp.rs:230:72
...
```

An update to latest asn1 release 0.6.4 solves the problem. Could you please update the requirement in ``Cargo.toml`` and keep the requirements up to date? Fedora build system ignores ``Cargo.lock`` and only uses ``Cargo.toml``. The build system may use slightly older or newer packages if they are considered compatible according to ``Cargo.toml``.

Failed build: https://koji.fedoraproject.org/koji/taskinfo?taskID=76503160
Fixed build: https://koji.fedoraproject.org/koji/taskinfo?taskID=76504325
