### ISSUE TITLE
Upgrade windows builders to OpenSSL 1.0.2b and issue a release

### ISSUE THREAD

**Issue by alex** [pyca/cryptography#2024]
https://www.openssl.org/news/secadv_20150611.txt

**Comment by alex** [comment]
1.0.2c is being released today, we should ship that instead.

**Comment by reaperhulk** [comment]
http://slproweb.com/products/Win32OpenSSL.html made significant changes to the way they build OpenSSL that unfortunately breaks our build process. I am unfortunately not going to be able to investigate this for around a week, so hopefully someone else can pick up the torch and figure out if we can resolve this or if we need to start building our own OpenSSL libraries on Windows.

**Comment by reaperhulk** [comment]
http://slproweb.com/products/Win32OpenSSL.html made significant changes to the way they build OpenSSL that unfortunately breaks our build process. I am sadly not going to be able to investigate this for around a week, so hopefully someone else can pick up the torch and figure out if we can resolve this or if we need to start building our own OpenSSL libraries on Windows.

**Comment by schlenk** [comment]
It should be easy to fix. They just moved the built static libraries into extra directories, so fixing up the LIB path and maybe the library names should be enough.

**Comment by reaperhulk** [comment]
@schlenk really? I tried using it and was getting errors that suggested more serious issues, but I didn't investigate. Have you successfully built against the 1.0.2c build provided by slproweb?

**Comment by schlenk** [comment]
@reaperhulk Okay, just tried and you are right, it IS a more serious problem.

For 2.7 builds i get this error a few times:

    ssleay32mt.lib(t1_lib.obj) : error LNK2001: unresolved external symbol ___report_rangecheckfailure

This means the guys compiling openssl changed their compiler version to a newer one with the recommended /GS switch (at least VS2012), as __report_rangecheckfailure is a feature of newer msvcrt libraries that doesn't work when trying to use it with a VS2008 or VS2010 compiler.

It is only a problem with the static library of course, but as that is the default it sucks.

**Comment by reaperhulk** [comment]
Well it turns out compiling it yourself isn't super hard so I've got a static 64-bit 1.0.2c build (and I'll build a 32-bit soon). Anybody have opinions on what our default configuration flags should be? What do you build with @schlenk?

**Comment by schlenk** [comment]
@reaperhulk Make sure you have 'nasm' and build the assembly modules (ms\do_nasm.bat), otherwise it cannot use the AES-NI stuff. 
My default flags are probably not useful, as it is for a specialized system and i disable as much as possible (e.g. no DTLS, no ssl2, no ssl3, no comp and a few other things out).

It could be a good idea to disable all of the obviously broken stuff by default:

    no-ssl2 no-ssl3 no-comp

Compression is usually bad due to CRIME attacks, so using ``no-comp`` might makes sense (default for libressl).

Depending on the amount of backwards compat issues, kicking out even more things might make sense: RC4 comes to mind, maybe DES and a few others too.

**Comment by alex** [comment]
Probably we should start by using the same configuration flags as slproweb does?

**Comment by schlenk** [comment]
Or use the ones used by CPython for its ssl module. Both are valid starting points.

It all depends on how much 'handholding' for secure algorithms/settings cryptography wants to do. Default configuration includes all the old, outdated and insecure stuff to shoot yourself into the foot with.

**Comment by toast12** [comment]
When is the new version with openssl 1.0.2c going to be released? I needed it urgently.
I was also exploring the possibility of building this by dynamically linking openssl 1.0.1m. But running into an issue since it used libeay32mt.lib. Any idea how to resolve this? Thanks

**Comment by reaperhulk** [comment]
We have information about dynamic linking here: 
https://cryptography.io/en/latest/installation/#on-windows

I apologize for our slowness in releasing a static build with 1.0.2c. The installer we used for windows changed the way they do builds in a way that breaks compiling of Python modules so we need to build our own. That's not an excuse, but figuring out how we want to do that has been a slow process.

**Comment by toast12** [comment]
Thanks reaperhulk. I followed the instructions for dynamic linking and get these errors:

libeay32.lib(bss_sock.obj) : error LNK2019: unresolved external symbol __imp__closesocket@4 referenced in function _sock_free
libeay32.lib(bss_sock.obj) : error LNK2019: unresolved external symbol __imp__shutdown@8 referenced in function _sock_free
libeay32.lib(bss_sock.obj) : error LNK2019: unresolved external symbol __imp__WSAGetLastError@0 referenced in function _BIO_sock_should_retry
-
-
Added ws2_32.lib to the LIB environment variable but doesn't work. Any suggestions? Thanks

**Comment by reaperhulk** [comment]
Where are you getting your OpenSSL from? Are you compiling it yourself?

**Comment by toast12** [comment]
Yes, I am compiling openssl 1.0.1m myself. Should I switch to openssl 1.0.2c?

**Comment by reaperhulk** [comment]
It should work fine with 1.0.1m, but it's possible there's a bug here (we don't test dynamic linking any more...but clearly we probably should so this might result in a new builder job). If you're installing 0.9.1 what happens if you edit https://github.com/pyca/cryptography/blob/0.9.x/src/cryptography/hazmat/bindings/openssl/binding.py#L50 to add "gdi32", "user32", and "ws2_32"?

**Comment by toast12** [comment]
Great. They resolve most except the below:

libeay32.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp__CertFreeCertificateContext@4 referenced in function _capi_free_key
libeay32.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp__CertGetCertificateContextProperty@16 referenced in function _capi_get_prov_info
libeay32.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp__CertOpenStore@20 referenced in function _capi_open_store
libeay32.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp__CertFindCertificateInStore@24 referenced in function _capi_find_cert
libeay32.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp__CertEnumCertificatesInStore@8 referenced in function _capi_find_cert
libeay32.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp__CertCloseStore@8 referenced in function _capi_find_key

**Comment by reaperhulk** [comment]
add "crypt32" as well

**Comment by toast12** [comment]
Awesome. That worked! Thanks reaperhulk

**Comment by reaperhulk** [comment]
https://social.msdn.microsoft.com/Forums/vstudio/en-US/7abc7f63-c3a6-4a55-babc-6914870d4959/unresolved-external-symbol-reportrangecheckfailure (just a note to myself about the rangecheck issues we've had with the slproweb OpenSSL build)

**Comment by toast12** [comment]
Hi reaperhulk, one quick and hopefully last question: Build is complete and cryptography imports fine. But I am not sure how to verify the openssl version. Before import testing, should I set LIB and INCLUDE for it to find openssl?

**Comment by schlenk** [comment]
@toast12: The libeay32mt.lib name is an artifact from the naming used by slprowebs openssl distro. It is just the usual static library created by the openssl build when you run `nmake -f ms\nt.mak` only renamed from libeay32.lib to libeay32mt.lib. So if you built openssl yourself, you could simply rename the static lib and link statically. 
Dynamic linking works too, but there are some pitfalls if you do that. If someone else dumps libeay32.dll files in the windows system dir (slproweb's installer offers this horribly bad choice by default) and the versions do not match, e.g. openssl 1.0.1 vs 1.0.2 it breaks your cryptography build on load (unless you mess around with manifests or put the libeay32.dll in the right places (same dir as the cryptography.pyd's) to get loaded properly).

**Comment by toast12** [comment]
Thanks for your inputs schlenk. But for some reason, I will need to build this dynamically. My build works fine but I cannot verify if openssl is dynamically linked. Any idea how to do this? Thanks

**Comment by toast12** [comment]
Never mind, I figured it out. Verified using python-openssl

**Comment by toast12** [comment]
Well, I think there is a problem here. Even if I build it by dynamically linking openssl, it still statically links it. So even if I have a different openssl version in my environment, it still uses the version that it was built it. Not sure if we ever tested dynamic linking piece?

**Comment by Ayrx** [comment]
@toast12 You did set the `PYCA_WINDOWS_LINK_TYPE ` environmental variable as per https://cryptography.io/en/latest/installation/#on-windows right?

**Comment by toast12** [comment]
yes i did. It still shows the openssl version with which it was built

**Comment by alex** [comment]
This is fixed with the 0.9.2 release. Sorry this took so long, we now build our own OpenSSL for windows, so it should be way faster to do these in the future.
