### PR TITLE
OpenSSL 1.0.2o has switched to winsock2

### PR DESCRIPTION
**Pull request by thierryba**
So here we need to make sure we don't simply include windows but only the parts that we want.

### CODE REVIEW

**Comment by alex** [comment]
Can you explain what problem this is solving? I just realized we don't have CI for Windows+1.0.2, we only test 1.1.0 with Windows in CI.

Do we fail to build on 1.0.2 on Windows?

Thanks!

**Comment by thierryba** [comment]
Yes it fails with toms of errors about symbols being redeclared with different linkage type. That seems to be happening from including both winsock 1 and 2.
So here I'm define WIN32_LEAN_AND_MEAN to avoid including the whole windows world in 1 include statement ;). And then the only thing that was still needed was to add wincrypt.h

**Comment by thierryba** [comment]
Of course from the logs it looks like for some other setup this is failing...

**Comment by reaperhulk** [comment]
Looks like `    build\temp.win32-2.7\Release\_openssl.c(2285) : error C2079: 'tv' uses undefined struct 'timeval'`

I believe that comes from `Winsock2.h` so that might be required as well?

**Comment by thierryba** [comment]
let me add it... but it might then fail because openssl prior to 1.0.2o is including winsock.h...

**Comment by reaperhulk** [comment]
Well this passes our CI -- @thierryba are you able to confirm if this works on OpenSSL < 1.0.2o?

**Comment by reaperhulk** [comment]
Thank you for the contribution!
