### PR TITLE
#9969 Expose SSL_session_reused.

### LINKED ISSUE #9969: SSL_session_reused bindings not available
Hi,

I might be missing something here.

I see that `SSL_session_reused` is defined here, but I can't acess it via the bindings

https://github.com/pyca/cryptography/blob/f69f27b1dd20ad2d24f48053a72545527e808104/src/_cffi_src/openssl/ssl.py#L410-L412

I am using Ubuntu 23.10 , with default py3 and latest cryptography installed in a virtualenv

```
$ virtualenv venv
$ . venv/bin/activate
$ pip install cryptography
$ python
Python 3.11.6 (main, Oct  8 2023, 05:06:43) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cryptography.hazmat.bindings.openssl.binding import Binding
>>> binding = Binding()
>>> binding.init_static_locks()

>>> binding.lib.SSL_session_reused
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'lib' has no attribute 'SSL_session_reused'

>>> binding.lib.SSL_select_next_proto
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'lib' has no attribute 'SSL_select_next_proto'

>>> binding.lib.SSL_CTX_set_alpn_protos
<built-in method SSL_CTX_set_alpn_protos of _cffi_backend.Lib object at 0x7fe38561bab0>
>>> 
```

```
$ python -m pip freeze
cffi==1.16.0
cryptography==41.0.7
pycparser==2.21
```

--------

I don't know why `SSL_CTX_set_alpn_protos` is available but `SSL_session_reused` and other functions are not available.

This was working in `cryptography==39.0.2`

I guess that this might be part of 40.0.0 

> Removed many unused CFFI OpenSSL bindings. This will not impact you unless you are using cryptography to directly invoke OpenSSL's C API. Note that these have never been considered a stable, supported, public API by cryptography, this note is included as a courtesy.

--------

I think that `SSL_session_reused` is very important as it is critical for implemeting FTPS server-side session reusal validation.

The `SSL_set_session` that is already avaiable, is used for the FTPS client-side part.

----------

Thanks

### PR DESCRIPTION
**Pull request by adiroiban**
Fixes #9969 

This (re)adds the `SSL_session_reused` API.

I think that this API is criticial.

First, this complements the already supported `int SSL_set_session(SSL *, SSL_SESSION *);
` to allow you to verify that after the handshake the session was reused.

Second, when implementing an FTPS server, this API is the only way to make sure you don't end up with hijacked FTP data connection.

I only added a simple tests to check that the API is there.

Let me know if more tests are required.

Thanks

### CODE REVIEW

**Comment by adiroiban** [comment]
This is read for review. Thanks!

**Comment by adiroiban** [comment]
I now see https://github.com/pyca/cryptography/issues/8675 

There are 2 things here: session cache vs session reuse.

The server/client can have session cache disabled and still reuse the session.

For example a session is initiated between server and client via connection A.

The client can initiate a new connection B to the server and setup the connection B via `session_a = SSL_get1_session(connection_a) -> SSL_set_session(connection_b, session_a)`

File: tests/hazmat/bindings/test_openssl.py [hunk 1]
```diff
@@ -112,3 +112,16 @@ def test_rust_internal_error(self):
         assert error.reason == b.lib.EVP_R_DATA_NOT_MULTIPLE_OF_BLOCK_LENGTH
         if not b.lib.CRYPTOGRAPHY_IS_BORINGSSL:
             assert b"data not multiple of block length" in error.reason_text
+
+    def test_ssl_session_reused_new(self):
```
Comment (alex) [inline tests/hazmat/bindings/test_openssl.py:116]: No need for a test, we don't add them for all bindings.

File: src/_cffi_src/openssl/ssl.py [hunk 2]
```diff
@@ -142,6 +142,7 @@
 const char *SSL_state_string_long(const SSL *);
 SSL_SESSION *SSL_get1_session(SSL *);
 int SSL_set_session(SSL *, SSL_SESSION *);
+int SSL_session_reused(const SSL *ssl);
```
Comment (alex) [inline src/_cffi_src/openssl/ssl.py:145]:
```suggestion
int SSL_session_reused(const SSL *);
```

File: tests/hazmat/bindings/test_openssl.py (hunk 1 above)
Comment (adiroiban) [reply tests/hazmat/bindings/test_openssl.py:116]: Is this a request to remove the test?

I think that a test can help with any accedental removal of the API.

It can also serve as an example on how to use the API.

Comment (alex) [reply tests/hazmat/bindings/test_openssl.py:116]: Yes, please remove the test.

**Comment by adiroiban** [comment]
I have removed the test. I was not expecting a request to submit a PR without tests.

I don't understand why is bad to have that test.

The test was kind a reminder that the binding in important and it should not be removed at the next "great purge".

No hard feelings. I am happy to have the new API available with or without tests.
I have automated tests for this API in my project, so that's fine be me.

Thanks for maintaining `cryptography`. Much appreciated.

**Review by alex — APPROVED** [review]
The reason we don't add tests for bindings is that they're not actually testing anything about this project, except that we bound the function correctly -- but that's handled in other ways.

We'll know not to remove this because a) it'll be used in pyOpenSSL (which we test in CI), b) we check the commit history before removing something.
