### ISSUE TITLE
cryptography(master branch) library does not build/install on Ubuntu 14.04-32bit

### ISSUE THREAD

**Issue by chirag-jog** [pyca/cryptography#1134]
While trying to build cryptography library on i686 Ubuntu-14.04 server it fails with the following error; it works fine with the 64-bit version of Ubuntu-14.04:

```
building '_Cryptography_cffi_dd47c45axadb2f636' extension
i686-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_dd47c45axadb2f636.c -o /tmp/git/cryptography/cryptography/hazmat/bindings/__pycache__/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_dd47c45axadb2f636.o
cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_dd47c45axadb2f636.c:302:9: error: conflicting types for ‘AES_ctr128_encrypt’
    void AES_ctr128_encrypt(const unsigned char *, unsigned char *,
         ^
In file included from cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_dd47c45axadb2f636.c:165:0:
/usr/include/openssl/aes.h:120:6: note: previous declaration of ‘AES_ctr128_encrypt’ was here
 void AES_ctr128_encrypt(const unsigned char *in, unsigned char *out,
      ^
Traceback (most recent call last):
  File "setup.py", line 174, in <module>
    "test": PyTest,
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 971, in run_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "setup.py", line 100, in finalize_options
    self.distribution.ext_modules = get_ext_modules()
  File "setup.py", line 68, in get_ext_modules
    OpenSSLBinding().ffi.verifier.get_extension(),
  File "/tmp/git/cryptography/cryptography/hazmat/bindings/openssl/binding.py", line 87, in __init__
    self._ensure_ffi_initialized()
  File "/tmp/git/cryptography/cryptography/hazmat/bindings/openssl/binding.py", line 106, in _ensure_ffi_initialized
    libraries=libraries,
  File "/tmp/git/cryptography/cryptography/hazmat/bindings/utils.py", line 80, in build_ffi
    extra_link_args=extra_link_args,
  File "/usr/local/lib/python2.7/dist-packages/cffi-0.8.2-py2.7-linux-i686.egg/cffi/api.py", line 341, in verify
    lib = self.verifier.load_library()
  File "/usr/local/lib/python2.7/dist-packages/cffi-0.8.2-py2.7-linux-i686.egg/cffi/verifier.py", line 74, in load_library
    self._compile_module()
  File "/usr/local/lib/python2.7/dist-packages/cffi-0.8.2-py2.7-linux-i686.egg/cffi/verifier.py", line 139, in _compile_module
    outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
  File "/usr/local/lib/python2.7/dist-packages/cffi-0.8.2-py2.7-linux-i686.egg/cffi/ffiplatform.py", line 25, in compile
    outputfilename = _build(tmpdir, ext)
  File "/usr/local/lib/python2.7/dist-packages/cffi-0.8.2-py2.7-linux-i686.egg/cffi/ffiplatform.py", line 50, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.ffiplatform.VerificationError: CompileError: command 'i686-linux-gnu-gcc' failed with exit status 1
```
