### ISSUE TITLE
build from source on OS X 10.11 with Xcode installed uses missing symbol

### ISSUE THREAD

**Issue by ploxiln** [pyca/cryptography#3332]
see https://github.com/Homebrew/homebrew-core/pull/8046

summary: if you have Xcode installed on MacOS 10.11, instead of "Command Line Tools", then the toolchain includes headers that are "compatible with both 10.12 and 10.11" by including `SYS_getentropy` in `<sys/syscall.h>` but having `_getentropy` as a "weak symbol" on 10.11.

This results in "Symbol not found: _getentropy":

```
File "/usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
File "/usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 51, in <module>
    from cryptography.hazmat.bindings._openssl import ffi as _ffi
    ImportError: dlopen(/usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so, 2): Symbol not found: _getentropy
    Referenced from: /usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so
    Expected in: /usr/lib/libSystem.B.dylib in /usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so
```

The temporary fix for the above homebrew build was a tiny patch to `src/_cffi_src/openssl/src/osrandom_engine.h` to force CRYPTOGRAPHY_OSRANDOM_ENGINE_GETENTROPY to not be selected on MacOS 10.11. I guess you're supposed to have something like a configure script that attempts to both build and run a test executable to detect whether getentropy() is really available ... I dunno.

**Comment by reaperhulk** [comment]
Thanks for the report. We can probably work around this by doing a version check as well, bleh.

**Comment by reaperhulk** [comment]
We need to do a better job of runtime detection here. Our wheels are built on 10.10 right now so only users on 10.12 compiling it themselves are getting the getentropy path...

**Comment by ilovezfs** [comment]
@reaperhulk in case this helps, here's how some other upstreams have addressed the Xcode 8 + 10.11 issues:
https://github.com/jemalloc/jemalloc/commit/eb29d7ec0e2c4994e10ec40d42265a86e569500c
https://github.com/tarantool/tarantool/commit/d36ba2796839db0edd3c62e9048cd41b1ee08d1e
https://github.com/jsquyres/libfabric/commit/469779935f9995b88a6f486fe3c4c4496989af36

**Comment by reaperhulk** [comment]
Thanks @ilovezfs that is helpful. I thunk availability will work for our purposes

**Comment by ilovezfs** [comment]
Unfortunately it looks like there's a regression and this is back. certbot built with 2.0.2:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/certbot/0.17.0/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.17.0', 'console_scripts', 'certbot')()
  File "/usr/local/Cellar/certbot/0.17.0/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/Cellar/certbot/0.17.0/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2662, in load_entry_point
    return ep.load()
  File "/usr/local/Cellar/certbot/0.17.0/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2316, in load
    return self.resolve()
  File "/usr/local/Cellar/certbot/0.17.0/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2322, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/Cellar/certbot/0.17.0/libexec/lib/python2.7/site-packages/certbot/main.py", line 9, in <module>
    from acme import jose
  File "/usr/local/Cellar/certbot/0.17.0/libexec/lib/python2.7/site-packages/acme/jose/__init__.py", line 37, in <module>
    from acme.jose.interfaces import JSONDeSerializable
  File "/usr/local/Cellar/certbot/0.17.0/libexec/lib/python2.7/site-packages/acme/jose/interfaces.py", line 9, in <module>
    from acme.jose import util
  File "/usr/local/Cellar/certbot/0.17.0/libexec/lib/python2.7/site-packages/acme/jose/util.py", line 5, in <module>
    import OpenSSL
  File "/usr/local/Cellar/certbot/0.17.0/libexec/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/Cellar/certbot/0.17.0/libexec/lib/python2.7/site-packages/OpenSSL/rand.py", line 10, in <module>
    from OpenSSL._util import (
  File "/usr/local/Cellar/certbot/0.17.0/libexec/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/usr/local/Cellar/certbot/0.17.0/libexec/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: dlopen(/usr/local/Cellar/certbot/0.17.0/libexec/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so, 2): Symbol not found: _getentropy
  Referenced from: /usr/local/Cellar/certbot/0.17.0/libexec/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so
  Expected in: /usr/lib/libSystem.B.dylib
 in /usr/local/Cellar/certbot/0.17.0/libexec/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so
```

**Comment by ilovezfs** [comment]
2.0, 2.0.1, and 2.0.2 are all affected. 1.9 is not.

**Comment by alex** [comment]
@ilovezfs hmm, we compile our wheels with `-mmacosx-version-min=10.9`, I suspect homebrew will need to do the same.

**Comment by ilovezfs** [comment]
@alex we set MACOSX_DEPLOYMENT_TARGET=10.11 on 10.11, which should be equivalent. Like I said, this is a regression. It was fixed. Now it's not.

**Comment by ilovezfs** [comment]
@alex this is likely the breaking commit: https://github.com/pyca/cryptography/commit/b637aec1624e558b0e158064264a2523a4dcba31

**Comment by reaperhulk** [comment]
@ilovezfs I'm definitely confused here. `getentropy` should be weakly linked, so dyld should just set it to NULL at runtime on versions where it is unavailable. Setting MACOSX_DEPLOYMENT_TARGET to 10.11 should make all of that work...unless maybe `/usr/include/sys/random.h` doesn't have the declaration at all? Is the environment seeing this problem running the latest xcode tools for 10.11?

**Comment by ilovezfs** [comment]
@reaperhulk 

https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/5927/version=el_capitan/console
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/5927/version=el_capitan/testReport/brew-test-bot/el_capitan/config/

>Is the environment seeing this problem running the latest xcode tools for 10.11?

Yes
```
macOS: 10.11.6-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
```

>unless maybe /usr/include/sys/random.h doesn't have the declaration at all?

`/usr/include/sys/random.h` (if it exists, i.e. if the CLT is installed) does not:
```
Mac-TMP:~ joe$ grep -r getentropy /usr/include
/usr/include/python2.7/pyconfig.h:/* Define to 1 if you have the `getentropy' function. */
```

But the SDK does
```
iMac-TMP:~ joe$ cd /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
iMac-TMP:MacOSX10.12.sdk joe$ grep -r getentropy usr/include
usr/include/python2.7/pyconfig.h:/* Define to 1 if you have the `getentropy' function. */
usr/include/sys/random.h:int getentropy(void* buffer, size_t size);
usr/include/sys/syscall.h:#define	SYS_getentropy     500
```

And we set the `SDKROOT` environment variable to `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk`.

**Comment by ilovezfs** [comment]
@reaperhulk By the way if there's any dummy C programs you'd like me to test to clarify they behavior, I'd be happy to.

**Comment by reaperhulk** [comment]
Okay, so this works on 10.12 but can you confirm it fails on 10.11?

```c
#include <Availability.h>
#include <string.h>
#include <sys/random.h>
#include <stdio.h>


int main(void) {
    if (&getentropy == NULL) {
        printf("no getentropy");
    } else {
        printf("getentropy is present");
    }
    return 0;
}
```

Does this work?

```c
#include <Availability.h>
#include <string.h>
#include <sys/random.h>
#include <stdio.h>

extern int getentropy(void* buffer, size_t size) __attribute((weak_import));

int main(void) {
    if (&getentropy == NULL) {
        printf("no getentropy");
    } else {
        printf("getentropy is present");
    }
    return 0;
}
```

**Comment by ilovezfs** [comment]
```
bash-3.2$ vi crypto.c
bash-3.2$ clang crypto.c 
In file included from crypto.c:3:
/usr/include/sys/random.h:37:32: error: unknown type name 'u_int'
void read_random(void* buffer, u_int numBytes);
                               ^
/usr/include/sys/random.h:38:33: error: unknown type name 'u_int'
void read_frandom(void* buffer, u_int numBytes);
                                ^
/usr/include/sys/random.h:39:33: error: unknown type name 'u_int'
int  write_random(void* buffer, u_int numBytes);
                                ^
crypto.c:8:10: error: use of undeclared identifier 'getentropy'
    if (&getentropy == NULL) {
         ^
4 errors generated.
bash-3.2$ export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
bash-3.2$ clang crypto.c 
bash-3.2$ ./a.out 
getentropy is presentbash-3.2$ 
bash-3.2$ rm a.out 
bash-3.2$ export MACOSX_DEPLOYMENT_TARGET=10.11
bash-3.2$ clang crypto.c 
bash-3.2$ ./a.out 
getentropy is presentbash-3.2$ 
bash-3.2$ vi crypto2.c
bash-3.2$ unset SDKROOT
bash-3.2$ unset MACOSX_DEPLOYMENT_TARGET
bash-3.2$ clang crypto2.c 
In file included from crypto2.c:3:
/usr/include/sys/random.h:37:32: error: unknown type name 'u_int'
void read_random(void* buffer, u_int numBytes);
                               ^
/usr/include/sys/random.h:38:33: error: unknown type name 'u_int'
void read_frandom(void* buffer, u_int numBytes);
                                ^
/usr/include/sys/random.h:39:33: error: unknown type name 'u_int'
int  write_random(void* buffer, u_int numBytes);
                                ^
3 errors generated.
bash-3.2$ export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
bash-3.2$ clang crypto2.c 
bash-3.2$ ./a.out 
no getentropybash-3.2$ 
bash-3.2$ rm a.out 
bash-3.2$ export MACOSX_DEPLOYMENT_TARGET=10.11
bash-3.2$ clang crypto2.c 
bash-3.2$ ./a.out 
no getentropybash-3.2$ 
bash-3.2$
```

**Comment by reaperhulk** [comment]
Okay, so the bug is that we improperly expected getentropy to be declared as a weakly imported function even on OS versions where it doesn't exist at all. If you build on 10.12 it works everywhere because it properly weak links getentropy and uses it as appropriate, but if built on 10.11 or earlier it will fais on anything other than 10.12 as getentropy will not be weakly linked.

The fix should just be to add `extern int getentropy(void* buffer, size_t size) __attribute((weak_import));` as a forward decl.

I'll go ahead and put in a PR. @ilovezfs would you be able to test that it works as you expect once it's up?

**Comment by ilovezfs** [comment]
>I'll go ahead and put in a PR. @ilovezfs would you be able to test that it works as you expect once it's up?

Yup

**Comment by reaperhulk** [comment]
#3841 hopefully works 😬

**Comment by ilovezfs** [comment]
@reaperhulk indeed it does!
